<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>realsense_bringup</name>
  <version>0.1.0</version>
  <description>Launch and RViz configuration for Intel RealSense D435i</description>
  <maintainer email="kazu0.4koi@gmail.com">kazuo-yokoi</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
