"""Pure-numpy tests for the offline reach solver against the real geometry.

No ROS runtime. The URDF fixture is generated by expanding the combined xacro
(see conftest.py); if xacro is unavailable the tests skip rather than fail, so
the suite still runs on a machine without ROS.
"""

import numpy as np
import pytest

from so101_bringup.cartesian_math import ARM_JOINTS, CONTROLLED_JOINTS, SerialChain, prefixed
from so101_bringup.reach_solver import (
    ITERATION_LIMIT,
    SOLVED,
    STALLED,
    SolverConfig,
    pinned_joints,
    solve,
)

PREFIX = "arm_"
BASE = PREFIX + "base_link"
TIP = PREFIX + "gripper_frame_link"


@pytest.fixture(scope="module")
def chain(combined_urdf):
    return SerialChain.from_urdf(combined_urdf, BASE, TIP)


@pytest.fixture(scope="module")
def limits(chain):
    return chain.limits(prefixed(CONTROLLED_JOINTS, PREFIX))


def zero_pose():
    return np.zeros(5)


def tip_at(chain, positions):
    tip, _ = chain.position_and_jacobian(
        dict(zip(prefixed(ARM_JOINTS, PREFIX), positions)),
        prefixed(CONTROLLED_JOINTS, PREFIX),
    )
    return tip


def test_chain_has_five_revolute_joints(chain):
    movable = [joint for joint in chain.joints if joint.joint_type != "fixed"]
    assert [joint.name for joint in movable] == prefixed(ARM_JOINTS, PREFIX)


def test_all_controlled_joints_have_finite_limits(limits):
    assert np.isfinite(np.array(limits)).all()
    for lower, upper in limits:
        # The solver clamps with a 0.10 rad margin on each side; a joint whose
        # range is narrower than that would be pinned at every pose.
        assert upper - lower > 0.20


def test_reaches_a_grid_of_in_workspace_targets(chain, limits):
    """Targets generated from real poses must be reachable from zero."""
    unreached = []
    for pan in (-0.6, 0.0, 0.6):
        for lift in (-0.5, 0.0):
            for elbow in (0.4, 1.0):
                pose = np.array([pan, lift, elbow, 0.2, 0.0])
                target = tip_at(chain, pose)
                result = solve(chain, zero_pose(), target, limits, prefix=PREFIX)
                if not result.solved:
                    unreached.append((pose.tolist(), result.status, result.residual))
    assert unreached == []


def test_solution_actually_puts_the_tip_on_the_target(chain, limits):
    target = tip_at(chain, np.array([0.3, -0.4, 0.9, 0.1, 0.0]))
    result = solve(chain, zero_pose(), target, limits, prefix=PREFIX)
    assert result.solved
    assert np.linalg.norm(tip_at(chain, result.positions) - target) < 0.005


def test_far_target_is_reported_unreachable_not_solved(chain, limits):
    result = solve(chain, zero_pose(), np.array([2.0, 0.0, 0.5]), limits, prefix=PREFIX)
    assert result.status in (STALLED, ITERATION_LIMIT)
    assert not result.solved
    assert result.residual > 0.005


def test_unreachable_target_names_the_pinned_joints(chain, limits):
    """Reaching straight backwards pins shoulder_pan at its limit."""
    result = solve(chain, zero_pose(), np.array([-0.5, 0.0, 0.1]), limits, prefix=PREFIX)
    assert not result.solved
    assert result.pinned, "unreachable target should name at least one pinned joint"
    assert all(name.startswith(PREFIX) for name in result.pinned)


def test_solution_never_violates_joint_limits(chain, limits):
    margin = SolverConfig().joint_limit_margin
    for target in (
        np.array([2.0, 0.0, 0.5]),
        np.array([0.0, 0.0, -1.0]),
        np.array([0.2, 0.2, 0.2]),
        np.array([-0.5, 0.0, 0.1]),
    ):
        result = solve(chain, zero_pose(), target, limits, prefix=PREFIX)
        for value, (lower, upper) in zip(result.positions[:4], limits):
            assert lower + margin - 1e-9 <= value <= upper - margin + 1e-9


def test_wrist_roll_is_preserved(chain, limits):
    start = np.array([0.0, 0.0, 0.0, 0.0, 0.7])
    target = tip_at(chain, np.array([0.2, -0.3, 0.8, 0.1, 0.7]))
    result = solve(chain, start, target, limits, prefix=PREFIX)
    assert result.positions[4] == pytest.approx(0.7)


def test_already_at_target_returns_immediately(chain, limits):
    target = tip_at(chain, zero_pose())
    result = solve(chain, zero_pose(), target, limits, prefix=PREFIX)
    assert result.solved
    assert result.iterations == 1


def test_pinned_joints_detects_both_bounds():
    limits = [(-1.0, 1.0), (-1.0, 1.0), (-1.0, 1.0)]
    positions = np.array([-0.9, 0.0, 0.9])
    assert pinned_joints(positions, ["a", "b", "c"], limits, margin=0.1) == ["a", "c"]
